version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: 'database'
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db1
       MYSQL_USER: asmae
       MYSQL_PASSWORD: asmae123
   api:
     container_name: 'api'
     build: .
     ports:
       - "3000:3000"
     links:
       - db
     depends_on:
       - db
     restart: always
     volumes:
        - ./server/:/usr/src/app
     entrypoint: tail -f /dev/null
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     ports :
        - "8081:80"
     environment:
        MYSQL_USERNAME: asmae
        MYSQL_PASSWORD: asmae123 
        MYSQL_ROOT_PASSWORD: root
     links:
        - db
volumes:
    db_data: {}